Normalize LF line endings for s6 scripts (fixing api flappin)

diff --git a/docker/rootfs/etc/cont-finish.d/90-openplc-save b/docker/rootfs/etc/cont-finish.d/90-openplc-save
--- a/docker/rootfs/etc/cont-finish.d/90-openplc-save
+++ b/docker/rootfs/etc/cont-finish.d/90-openplc-save
@@ -1,3 +1,9 @@
 #!/command/with-contenv sh
 set -eu
-/opt/himalia/openplc/openplc-save.sh || true
+
+if /opt/himalia/openplc/openplc-save.sh; then
+  echo "[cont-finish] OpenPLC save: OK"
+else
+  rc=$?
+  echo "[cont-finish] OpenPLC save: FAILED (rc=${rc})" >&2
+fi
